categories: Categories
category: Category
search: Search
tags: Tags
tag: Tag
tagcloud: "Tag Cloud"
prev: Prev
next: Next
old: Old
new: New
comment: Comments
contents: Contents
archive_a: Archives
archive_b: "Archives: %s"
page: "Page %d"
recent_posts: "Recent Posts"
menu: Menu
links: Links
rss: RSS
showsidebar: "Show Sidebar"
hidesidebar: "Hide Sidebar"
updated: Updated
archive_date: "MMMM YYYY"